///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

interface ProtocolValidator {
    /**
     * Validate if a Message is compatible with the version
     * @param mesg Message to validate
     * @return true if message is compatible false otherwise
     */
    boolean validateMesg(Mesg mesg);

    /**
     * Validate if a Message Definition is compatible with the version
     * @param defn Definition
     * @return true if Definition is compatible false otherwise
     */
    boolean validateMesgDefn(MesgDefinition defn);
}
