///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITDeviceAuxBatteryInfoMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// DeviceIndex 
- (BOOL)isDeviceIndexValid;
- (FITDeviceIndex)getDeviceIndex;
- (void)setDeviceIndex:(FITDeviceIndex)deviceIndex;
// BatteryVoltage 
- (BOOL)isBatteryVoltageValid;
- (FITFloat32)getBatteryVoltage;
- (void)setBatteryVoltage:(FITFloat32)batteryVoltage;
// BatteryStatus 
- (BOOL)isBatteryStatusValid;
- (FITBatteryStatus)getBatteryStatus;
- (void)setBatteryStatus:(FITBatteryStatus)batteryStatus;
// BatteryIdentifier 
- (BOOL)isBatteryIdentifierValid;
- (FITUInt8)getBatteryIdentifier;
- (void)setBatteryIdentifier:(FITUInt8)batteryIdentifier;

@end

NS_ASSUME_NONNULL_END
