///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITSdmProfileMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// Enabled 
- (BOOL)isEnabledValid;
- (FITBool)getEnabled;
- (void)setEnabled:(FITBool)enabled;
// SdmAntId 
- (BOOL)isSdmAntIdValid;
- (FITUInt16z)getSdmAntId;
- (void)setSdmAntId:(FITUInt16z)sdmAntId;
// SdmCalFactor 
- (BOOL)isSdmCalFactorValid;
- (FITFloat32)getSdmCalFactor;
- (void)setSdmCalFactor:(FITFloat32)sdmCalFactor;
// Odometer 
- (BOOL)isOdometerValid;
- (FITFloat32)getOdometer;
- (void)setOdometer:(FITFloat32)odometer;
// SpeedSource 
- (BOOL)isSpeedSourceValid;
- (FITBool)getSpeedSource;
- (void)setSpeedSource:(FITBool)speedSource;
// SdmAntIdTransType 
- (BOOL)isSdmAntIdTransTypeValid;
- (FITUInt8z)getSdmAntIdTransType;
- (void)setSdmAntIdTransType:(FITUInt8z)sdmAntIdTransType;
// OdometerRollover 
- (BOOL)isOdometerRolloverValid;
- (FITUInt8)getOdometerRollover;
- (void)setOdometerRollover:(FITUInt8)odometerRollover;

@end

NS_ASSUME_NONNULL_END
