///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITWeatherAlertMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// ReportId 
- (BOOL)isReportIdValid;
- (NSString *)getReportId;
- (void)setReportId:(NSString *)reportId;
// IssueTime 
- (BOOL)isIssueTimeValid;
- (FITDate *)getIssueTime;
- (void)setIssueTime:(FITDate *)issueTime;
// ExpireTime 
- (BOOL)isExpireTimeValid;
- (FITDate *)getExpireTime;
- (void)setExpireTime:(FITDate *)expireTime;
// Severity 
- (BOOL)isSeverityValid;
- (FITWeatherSeverity)getSeverity;
- (void)setSeverity:(FITWeatherSeverity)severity;
// Type 
- (BOOL)isTypeValid;
- (FITWeatherSevereType)getType;
- (void)setType:(FITWeatherSevereType)type;

@end

NS_ASSUME_NONNULL_END
