///////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin International, Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2022 Garmin International, Inc.
///////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.84Release
// Tag = production/akw/21.84.00-0-g894a113c
///////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>
#include <string>

#import "FITTypes.h"

typedef std::wstring FIT_WSTRING;   // Returned by message/field "Get" APIs and required by "Set" APIs. Encoding defined in fit_config.hpp.
typedef const FIT_WSTRING * FIT_CONST_WSTRING_PTR;
#define FIT_WSTRING_INVALID   (FIT_WSTRING())


NS_ASSUME_NONNULL_BEGIN

@interface FITString : NSObject

+ (FIT_WSTRING) fitStringWithString: (NSString *) string;
+ (NSString *) stringWithFITString: (FIT_WSTRING) string;
@end

NS_INLINE FIT_WSTRING FITStringFromString(NSString * string) {
    return [FITString fitStringWithString:string];
}

NS_INLINE NSString * StringFromFITString(FIT_WSTRING string) {
    return [FITString stringWithFITString:string];
}

NS_ASSUME_NONNULL_END
